/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Dither_AntiAliasing */

#ifndef _Included_org_zoy_caca_Dither_AntiAliasing
#define _Included_org_zoy_caca_Dither_AntiAliasing
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
