/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Canvas_Handle */

#ifndef _Included_org_zoy_caca_Canvas_Handle
#define _Included_org_zoy_caca_Canvas_Handle
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
