/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Font */

#ifndef _Included_org_zoy_caca_Font
#define _Included_org_zoy_caca_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Font
 * Method:    loadFont
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zoy_caca_Font_loadFont__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zoy_caca_Font
 * Method:    loadFont
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_zoy_caca_Font_loadFont___3B
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_zoy_caca_Font
 * Method:    getFontNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Font_getFontNames
  (JNIEnv *, jclass);

/*
 * Class:     org_zoy_caca_Font
 * Method:    getFontWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Font_getFontWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Font
 * Method:    getFontHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Font_getFontHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Font
 * Method:    getFontBlocks
 * Signature: (J)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Font_getFontBlocks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Font
 * Method:    freeFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Font_freeFont
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
