/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Event_Key */

#ifndef _Included_org_zoy_caca_Event_Key
#define _Included_org_zoy_caca_Event_Key
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
