/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Canvas_Cursor */

#ifndef _Included_org_zoy_caca_Canvas_Cursor
#define _Included_org_zoy_caca_Canvas_Cursor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
