/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Event */

#ifndef _Included_org_zoy_caca_Event
#define _Included_org_zoy_caca_Event
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventKeyCh
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventKeyCh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventKeyUtf32
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventKeyUtf32
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventKeyUtf8
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Event_getEventKeyUtf8
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventMouseButton
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventMouseButton
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventMouseX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventMouseX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventMouseY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventMouseY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventResizeWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventResizeWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    getEventResizeHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Event_getEventResizeHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Event
 * Method:    freeEvent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Event_freeEvent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
