/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Canvas */

#ifndef _Included_org_zoy_caca_Canvas
#define _Included_org_zoy_caca_Canvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCursorX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCursorX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCursorY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCursorY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCursorXY
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCursorXY
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getHandleX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getHandleX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getHandleY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getHandleY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setHandleXY
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setHandleXY
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    createCanvas
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_zoy_caca_Canvas_createCanvas
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCanvasWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCanvasHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    clearCanvas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_clearCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasChar
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCanvasChar
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    putCanvasChar
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_putCanvasChar
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    putCanvasString
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_putCanvasString
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    blitCanvas
 * Signature: (JIIJJ)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_blitCanvas
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasBoundaries
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasBoundaries
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    invertCanvas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_invertCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    flipCanvas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_flipCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    flopCanvas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_flopCanvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    rotateCanvas180
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_rotateCanvas180
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    rotateCanvasLeft
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_rotateCanvasLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    rotateCanvasRight
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_rotateCanvasRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    stretchCanvasLeft
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_stretchCanvasLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    stretchCanvasRight
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_stretchCanvasRight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasAttribute
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCanvasAttribute
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasAttribute
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasAttribute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    putCanvasAttribute
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_putCanvasAttribute
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasColorAnsi
 * Signature: (JBB)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasColorAnsi
  (JNIEnv *, jclass, jlong, jbyte, jbyte);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasColorArgb
 * Signature: (JSS)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasColorArgb
  (JNIEnv *, jclass, jlong, jshort, jshort);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawLine
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawLine
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawPolyline
 * Signature: (J[I[II)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawPolyline
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawThinLine
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawThinLine
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawThinPolyline
 * Signature: (J[I[I)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawThinPolyline
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawCircle
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawCircle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawEllipse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawEllipse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawThinEllipse
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawThinEllipse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasFillEllipse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasFillEllipse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawBox
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawBox
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawThinBox
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawThinBox
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawCp437Box
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawCp437Box
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasFillBox
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasFillBox
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawTriangle
 * Signature: (JIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawTriangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDrawThinTriangle
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDrawThinTriangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasFillTriangle
 * Signature: (JIIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasFillTriangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zoy_caca_Canvas_getCanvasFrameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasFrame
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasFrame
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    getCanvasFrameName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Canvas_getCanvasFrameName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    setCanvasFrameName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_setCanvasFrameName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    createCanvasFrame
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_createCanvasFrame
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    freeCanvasFrame
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_freeCanvasFrame
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasRender
 * Signature: (JJ[BIII)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasRender
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    canvasDitherBitmap
 * Signature: (JIIIIJ[B)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_canvasDitherBitmap
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong, jbyteArray);

/*
 * Class:     org_zoy_caca_Canvas
 * Method:    freeCanvas
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Canvas_freeCanvas
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
