/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Display_Driver */

#ifndef _Included_org_zoy_caca_Display_Driver
#define _Included_org_zoy_caca_Display_Driver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
