/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Caca */

#ifndef _Included_org_zoy_caca_Caca
#define _Included_org_zoy_caca_Caca
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Caca
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Caca_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
