/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Dither */

#ifndef _Included_org_zoy_caca_Dither
#define _Included_org_zoy_caca_Dither
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Dither
 * Method:    createDither
 * Signature: (IIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_zoy_caca_Dither_createDither
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherPalette
 * Signature: (J[I[I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherPalette
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherBrightness
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherBrightness
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherBrightness
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_zoy_caca_Dither_getDitherBrightness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherGamma
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherGamma
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherGamma
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_zoy_caca_Dither_getDitherGamma
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherContrast
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherContrast
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherContrast
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_zoy_caca_Dither_getDitherContrast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherAntiAliasingList
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Dither_getDitherAntiAliasingList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherAntiAliasing
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherAntiAliasing
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherAntiAliasing
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Dither_getDitherAntiAliasing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherColorList
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Dither_getDitherColorList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherColor
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherColor
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherColor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Dither_getDitherColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherCharsetList
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Dither_getDitherCharsetList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherCharset
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherCharset
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherCharset
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Dither_getDitherCharset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherAlgorithmList
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_zoy_caca_Dither_getDitherAlgorithmList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    setDitherAlgorithm
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_setDitherAlgorithm
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    getDitherAlgorithm
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zoy_caca_Dither_getDitherAlgorithm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zoy_caca_Dither
 * Method:    freeDither
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zoy_caca_Dither_freeDither
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
