/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zoy_caca_Attribute */

#ifndef _Included_org_zoy_caca_Attribute
#define _Included_org_zoy_caca_Attribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToAnsi
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_zoy_caca_Attribute_attributeToAnsi
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToAnsiForeground
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_zoy_caca_Attribute_attributeToAnsiForeground
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToAnsiBackground
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_zoy_caca_Attribute_attributeToAnsiBackground
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToRgb12Foreground
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_zoy_caca_Attribute_attributeToRgb12Foreground
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToRgb12Background
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_zoy_caca_Attribute_attributeToRgb12Background
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zoy_caca_Attribute
 * Method:    attributeToArgb64
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zoy_caca_Attribute_attributeToArgb64
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
